# Generated by Django 4.0.4 on 2022-04-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=32)),
                ('contact_number', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=128)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
