# Generated by Django 4.0.4 on 2022-04-29 00:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('impression', models.PositiveIntegerField(default=0)),
                ('click', models.PositiveIntegerField(default=0)),
                ('conversion', models.PositiveSmallIntegerField(default=0)),
                ('cv', models.PositiveBigIntegerField(default=0)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisers.client')),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
