# Generated by Django 4.0.4 on 2022-04-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='ClientPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisers.client')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.platform')),
            ],
            options={
                'db_table': 'client_platform',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
                ('imporession', models.IntegerField()),
                ('click', models.IntegerField()),
                ('conversion', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('roas', models.FloatField()),
                ('cpc', models.FloatField()),
                ('cvr', models.FloatField()),
                ('cpa', models.FloatField()),
                ('client_platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.clientplatform')),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
