# Generated by Django 4.0.4 on 2022-04-28 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
